version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flowershop_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flowershop_db
      MYSQL_USER: flowershop_user
      MYSQL_PASSWORD: flowershop_pass
    ports:
      - "3306:3306"
    volumes:
      - flowershop_mysql_data:/var/lib/mysql

volumes:
  flowershop_mysql_data: